//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public long AreaId { get; set; }
        public string AreaName { get; set; }
        public string AreaDescription { get; set; }
        public long ProvinceId { get; set; }
        public string RecCreatedBy { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public System.DateTime RecLastUpdate { get; set; }
        public string RecUpdatedBy { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
